language: objective-c
branches:
  only:
    - travis+coveralls
before_install:
  - sudo easy_install cpp-coveralls
  - brew uninstall xctool
  - brew update
  - brew install xctool --HEAD
script:
  - xctool test ONLY_ACTIVE_ARCH=NO -project AOPProxy.xcodeproj -scheme "AOPProxy (OSX)"
after_success:
  - ./.coveralls.rb

